- src: geerlingguy.pip
  version: 2.0.0
- src: geerlingguy.git
  version: 2.36.1
- src: geerlingguy.java
  version: 4.3.0
- src: gantsign.maven
  version: 5.6.0
- src: geerlingguy.jenkins
  version: 3.7.0
- src: robertdebock.tomcat
  version: 5.3.4

